/* Copyright (C) 2010 *******************************************************************************
                                    杭州科强智能控制系统有限公司
=====================================================================================================
项目名称：T6F5平台注塑机控制系统
项目简介：
======================================== 文   件    信   息 =========================================
文件名称：CM_PeriPara.h    外设参数文件
适用范围：主机
建立时间：2026-5-7 9:20:15
RPHA版本：V208
特征代码：  0x88E6  
****************************************************************************************************/
#ifndef CM_PeriPara_h
    #define CM_PeriPara_h

#ifdef RPHA_c
    #define CM_PeriPara_ext
#else
    #define CM_PeriPara_ext extern
#endif

/*====================================== 全局有效宏及变量定义 ======================================*/
//外设参数数量
#define mPeriParaNum 512  //外设参数数量

//外设参数数组定义
CM_PeriPara_ext U32 PeriPara[mPeriParaNum];      //外设参数数组

//外设参数序号宏定义
#define mPara_PeriParaSum        0              //累加和校验码                              辅助用，下述机器参数累加和
#define mPara_J6hHydrContrWord   1              //液压控制字                               
#define mPara_J6hSetFlow1        2              //系统流量1                               
#define mPara_J6hSetPres1        3              //系统压力1                               
#define mPara_J6hSetFlow2        4              //系统流量2                               
#define mPara_J6hSetPres2        5              //系统压力2                               
#define mPara_J6hSetFlow3        6              //系统流量3                               
#define mPara_J6hSetPres3        7              //系统压力3                               
#define mPara_J6hSetFlow4        8              //系统流量4                               
#define mPara_J6hSetPres4        9              //系统压力4                               
#define mPara_J6hActContrWord1   10             //液压动作指令1                             
#define mPara_J6hActContrWord2   11             //液压动作指令2                             
#define mPara_J6hActContrWord3   12             //液压动作指令3                             
#define mPara_J6hActContrWord4   13             //液压动作指令4                             
#define mPara_J6hHydrStatusWord  14             //液压状态字                               
#define mPara_J6hOutFlow1        15             //输出速度1                               
#define mPara_J6hCurrPres1       16             //实际压力1                               
#define mPara_J6hOutFlow2        17             //输出速度2                               
#define mPara_J6hCurrPres2       18             //实际压力2                               
#define mPara_J6hOutFlow3        19             //输出速度3                               
#define mPara_J6hCurrPres3       20             //实际压力3                               
#define mPara_J6hOutFlow4        21             //输出速度4                               
#define mPara_J6hCurrPres4       22             //实际压力4                               
#define mPara_J6hHardwareVer     23             //硬件版本                                
#define mPara_J6hSoftwareVer     24             //软件版本                                
#define mPara_J6hModelInfo       25             //机型信息                                
#define mPara_J6hNotConnDriver   26             //主站未连接驱动器号记录                         
#define mPara_J6hGeneralKP       27             //通用KP                                
#define mPara_J6hGeneralKI       28             //通用KI                                
#define mPara_J6hGeneralKD       29             //通用KD                                
#define mPara_J6hInjectKP        30             //注射KP                                
#define mPara_J6hInjectKI        31             //注射KI                                
#define mPara_J6hInjectKD        32             //注射KD                                
#define mPara_J6hHoldPresKP      33             //保压KP                                
#define mPara_J6hHoldPresKI      34             //保压KI                                
#define mPara_J6hHoldPresKD      35             //保压KD                                
#define mPara_J6hSetPres         36             //设定压力                                
#define mPara_J6hSetFlow         37             //设定流量                                
#define mPara_J6hOutTorque       38             //输出扭矩                                
#define mPara_J6hOutRev          39             //输出转速                                
#define mPara_J6hCurrPres        40             //实际压力                                
#define mPara_J6hMotionErr       41             //运动卡error                            
#define mPara_J6hParaConfirm     42             //参数确认                                
#define mPara_J6hHydrIndex       43             //液压轴索引                               
#define mPara_J6hDriverIndex     44             //伺服轴索引                               
#define mPara_J6hParaConfig      45             //参数下载/备份/重置                          
#define mPara_J6hZeroSeek        46             //一键寻零/自学习                            
#define mPara_J6hDisabled        47             //断开使能                                
#define mPara_J6hParaInOrOut     48             //参数导入/导出                             
#define mPara_J6hImportFile      49             //导入文件选择                              
#define mPara_J6hSensorMinVol    50             //传感器最小电压                             
#define mPara_J6hSensorMaxVol    51             //传感器最大电压                             
#define mPara_J6hSensorPresRat   52             //传感器压力等级                             
#define mPara_J6hPresCurrVol     53             //压力传感器实际电压                           
#define mPara_J6hPresAccele      54             //压力环加速度                              
#define mPara_J6hPresDecele      55             //压力环减速度                              
#define mPara_J6hFlowComp        56             //给定流量补偿                              
#define mPara_J6hPres1           57             //1点压力                                
#define mPara_J6hPres2           58             //2点压力                                
#define mPara_J6hPres3           59             //3点压力                                
#define mPara_J6hPres4           60             //4点压力                                
#define mPara_J6hPres5           61             //5点压力                                
#define mPara_J6hPres6           62             //6点压力                                
#define mPara_J6hPres7           63             //7点压力                                
#define mPara_J6hPres8           64             //8点压力                                
#define mPara_J6hCompFlow1       65             //1点补偿流量                              
#define mPara_J6hCompFlow2       66             //2点补偿流量                              
#define mPara_J6hCompFlow3       67             //3点补偿流量                              
#define mPara_J6hCompFlow4       68             //4点补偿流量                              
#define mPara_J6hCompFlow5       69             //5点补偿流量                              
#define mPara_J6hCompFlow6       70             //6点补偿流量                              
#define mPara_J6hCompFlow7       71             //7点补偿流量                              
#define mPara_J6hCompFlow8       72             //8点补偿流量                              
#define mPara_J6hTorqueSlope     73             //扭矩释放斜率                              
#define mPara_J6hUnderflow       74             //底流                                  
#define mPara_J6hPresContrLimit  75             //压力控制上下限系数                           
#define mPara_J6hMaxPresLoadTor  76             //最大压力负载扭矩                            
#define mPara_J6hPresRelTorque   77             //泄压回拉扭矩                              
#define mPara_J6hPresRelMxNRev   78             //泄压最大负转速                             
#define mPara_J6hEndPresRelTor   79             //动作结束泄压扭矩系数                          
#define mPara_J6hPresContrAccu   80             //压力控制精度                              
#define mPara_J6hHydrConWordSDO  81             //液压控制字                               
#define mPara_J6hEnInjRigid      82             //注射刚性使能                              
#define mPara_J6hInjRigidPres    83             //注射刚性压力                              
#define mPara_J6hSetSpeed        84             //设定速度                                
#define mPara_J6hEncoderSpeed    85             //编码器速度                               
#define mPara_J6hSetTorque       86             //设定扭矩                                
#define mPara_J6hCurrTorque      87             //实际扭矩                                
#define mPara_J6hApparCurrent    88             //视在电流                                
#define mPara_J6hCurrentPeak     89             //电流尖峰值                               
#define mPara_J6hGenerVol        90             //母线电压                                
#define mPara_J6hGenerVolPeak    91             //母线电压尖峰值                             
#define mPara_J6hCurrVol         92             //实际输出电压                              
#define mPara_J6hSpeedRing       93             //速度环                                 
#define mPara_J6hSwitchFreq      94             //开关频率                                
#define mPara_J6hEncoderType     95             //编码器接口类型                             
#define mPara_J6hMotorZero       96             //电机零位                                
#define mPara_J6hDirSelec        97             //方向选择                                
#define mPara_J6hEnableState     98             //使能状态                                
#define mPara_J6hDriverVer       99             //驱动器版本                               
#define mPara_J6hDriver1Temp     100            //驱动器1温度                              
#define mPara_J6hDriver2Temp     101            //驱动器2温度                              
#define mPara_J6hDriver3Temp     102            //驱动器3温度                              
#define mPara_J6hDriver4Temp     103            //驱动器4温度                              
#define mPara_J6hDriver5Temp     104            //驱动器5温度                              
#define mPara_J6hDriver6Temp     105            //驱动器6温度                              
#define mPara_J6hDriver7Temp     106            //驱动器7温度                              
#define mPara_J6hDriver8Temp     107            //驱动器8温度                              
#define mPara_J6hMotor1Temp      108            //电机1温度                               
#define mPara_J6hMotor2Temp      109            //电机2温度                               
#define mPara_J6hMotor3Temp      110            //电机3温度                               
#define mPara_J6hMotor4Temp      111            //电机4温度                               
#define mPara_J6hMotor5Temp      112            //电机5温度                               
#define mPara_J6hMotor6Temp      113            //电机6温度                               
#define mPara_J6hMotor7Temp      114            //电机7温度                               
#define mPara_J6hMotor8Temp      115            //电机8温度                               
#define mPara_J6hMaxSpeed        116            //最大速度                                
#define mPara_J6hTorqueFactor    117            //扭矩因子                                
#define mPara_J6hDriEarWarnTemp  118            //驱动器预警温度                             
#define mPara_J6hDriWarnTemp     119            //驱动器报警温度                             
#define mPara_J6hMotoEarWarnTemp 120            //电机预警温度                              
#define mPara_J6hDMotoWarnTemp   121            //电机报警温度                              
#define mPara_J6hDri1ErrCode     122            //驱动器1故障代码                            
#define mPara_J6hDri2ErrCode     123            //驱动器2故障代码                            
#define mPara_J6hDri3ErrCode     124            //驱动器3故障代码                            
#define mPara_J6hDri4ErrCode     125            //驱动器4故障代码                            
#define mPara_J6hDri5ErrCode     126            //驱动器5故障代码                            
#define mPara_J6hDri6ErrCode     127            //驱动器6故障代码                            
#define mPara_J6hDri7ErrCode     128            //驱动器7故障代码                            
#define mPara_J6hDri8ErrCode     129            //驱动器8故障代码                            
#define mPara_J6hDri9ErrCode     130            //驱动器9故障代码                            
#define mPara_J6hDri10ErrCode    131            //驱动器10故障代码                           
#define mPara_J6hDri11ErrCode    132            //驱动器11故障代码                           
#define mPara_J6hDri12ErrCode    133            //驱动器12故障代码                           
#define mPara_J6hDri13ErrCode    134            //驱动器13故障代码                           
#define mPara_J6hDri14ErrCode    135            //驱动器14故障代码                           
#define mPara_J6hDriSearchAdd    136            //驱动器全地址搜索地址                          
#define mPara_J6hDriSearchDat    137            //驱动器全地址搜索内容                          
#define mPara_Peri_138           138            //                                    
#define mPara_Peri_139           139            //                                    
#define mPara_Peri_140           140            //                                    
#define mPara_Peri_141           141            //                                    
#define mPara_Peri_142           142            //                                    
#define mPara_Peri_143           143            //                                    
#define mPara_Peri_144           144            //                                    
#define mPara_Peri_145           145            //                                    
#define mPara_Peri_146           146            //                                    
#define mPara_Peri_147           147            //                                    
#define mPara_Peri_148           148            //                                    
#define mPara_Peri_149           149            //                                    
#define mPara_Peri_150           150            //                                    
#define mPara_Peri_151           151            //                                    
#define mPara_Peri_152           152            //                                    
#define mPara_Peri_153           153            //                                    
#define mPara_Peri_154           154            //                                    
#define mPara_Peri_155           155            //                                    
#define mPara_Peri_156           156            //                                    
#define mPara_Peri_157           157            //                                    
#define mPara_Peri_158           158            //                                    
#define mPara_Peri_159           159            //                                    
#define mPara_Peri_160           160            //                                    
#define mPara_Peri_161           161            //                                    
#define mPara_Peri_162           162            //                                    
#define mPara_Peri_163           163            //                                    
#define mPara_Peri_164           164            //                                    
#define mPara_Peri_165           165            //                                    
#define mPara_Peri_166           166            //                                    
#define mPara_Peri_167           167            //                                    
#define mPara_Peri_168           168            //                                    
#define mPara_Peri_169           169            //                                    
#define mPara_Peri_170           170            //                                    
#define mPara_Peri_171           171            //                                    
#define mPara_Peri_172           172            //                                    
#define mPara_Peri_173           173            //                                    
#define mPara_Peri_174           174            //                                    
#define mPara_Peri_175           175            //                                    
#define mPara_Peri_176           176            //                                    
#define mPara_Peri_177           177            //                                    
#define mPara_Peri_178           178            //                                    
#define mPara_Peri_179           179            //                                    
#define mPara_Peri_180           180            //                                    
#define mPara_Peri_181           181            //                                    
#define mPara_Peri_182           182            //                                    
#define mPara_Peri_183           183            //                                    
#define mPara_Peri_184           184            //                                    
#define mPara_Peri_185           185            //                                    
#define mPara_Peri_186           186            //                                    
#define mPara_Peri_187           187            //                                    
#define mPara_Peri_188           188            //                                    
#define mPara_Peri_189           189            //                                    
#define mPara_Peri_190           190            //                                    
#define mPara_Peri_191           191            //                                    
#define mPara_Peri_192           192            //                                    
#define mPara_Peri_193           193            //                                    
#define mPara_Peri_194           194            //                                    
#define mPara_Peri_195           195            //                                    
#define mPara_Peri_196           196            //                                    
#define mPara_Peri_197           197            //                                    
#define mPara_Peri_198           198            //                                    
#define mPara_Peri_199           199            //                                    
#define mPara_TDSDCurSel         200            //当前台达伺服驱动器序号选择                       
#define mPara_TDSetPres          201            //台达驱动器设置压力                           
#define mPara_TDSetFlow          202            //台达驱动器设置流量                           
#define mPara_Peri_203           203            //                                    
#define mPara_Peri_204           204            //                                    
#define mPara_Peri_205           205            //                                    
#define mPara_Peri_206           206            //                                    
#define mPara_Peri_207           207            //                                    
#define mPara_Peri_208           208            //                                    
#define mPara_Peri_209           209            //                                    
#define mPara_SDParaRestMode     210            //SD驱动器参数复位                           
#define mPara_SDSetMaxRpm        211            //SD驱动器最高转速                           
#define mPara_SDSetMaxPres       212            //SD驱动器最高压力                           
#define mPara_SDSpeedBandwidth   213            //SD驱动器速度带宽                           
#define mPara_SDSetPresPercMax   214            //SD驱动器设置压力最大百分比                      
#define mPara_SDSetPresPercMid   215            //SD驱动器设置压力中间百分比                      
#define mPara_SDSetPresPercMin   216            //SD驱动器设置压力最小百分比                      
#define mPara_SDSetFlowPercMin   217            //SD驱动器设置流量最小百分比                      
#define mPara_SDPGain1           218            //SD驱动器增益1                            
#define mPara_SDPGain2           219            //SD驱动器增益2                            
#define mPara_SDBasePres         220            //SD驱动器底压                             
#define mPara_SDMotorMaxFreq     221            //SD驱动器电机最大频率                         
#define mPara_SDMotorRatedFreq   222            //SD驱动器电机额定频率                         
#define mPara_SDMotorRatedVol    223            //SD驱动器电机额定电压                         
#define mPara_SDMotorRatedCur    224            //SD驱动器电机额定电流                         
#define mPara_SDMotorRatedPow    225            //SD驱动器电机额定功率                         
#define mPara_SDMotorRatedRpm    226            //SD驱动器电机额定转速                         
#define mPara_SDMotorMagnPoleNum 227            //SD驱动器电机额定磁极数                        
#define mPara_SDMotorInertia     228            //SD驱动器电机惯量                           
#define mPara_SDSysInertia       229            //SD驱动器系统惯量                           
#define mPara_SDForwAndReveCon   230            //SD驱动器正反转控制                          
#define mPara_SDAlarmPcs         231            //SD驱动器警报处理                           
#define mPara_SDMotorTempOver    232            //SD驱动器过温温度                           
#define mPara_SDMotorTempSnrType 233            //SD驱动器电机温度传感器类型                      
#define mPara_SDMotorPresSnrMinVol 234          //SD驱动器压力传感器最小电压                      
#define mPara_SDMotorParaSelfLearn 235          //SD驱动器电机参数自学习                        
#define mPara_SDPresConMode      236            //SD驱动器压力控制模式                         
#define mPara_SDEnableResrSel    237            //SD驱动器使能源选择                          
#define mPara_SDPara29           238            //SD驱动器参数29                           
#define mPara_SDPara30           239            //SD驱动器参数30                           
#define mPara_SDPara31           240            //SD驱动器参数31                           
#define mPara_SDPara32           241            //SD驱动器参数32                           
#define mPara_SDPara33           242            //SD驱动器参数33                           
#define mPara_SDPara34           243            //SD驱动器参数34                           
#define mPara_SDPara35           244            //SD驱动器参数35                           
#define mPara_SDPara36           245            //SD驱动器参数36                           
#define mPara_SDPara37           246            //SD驱动器参数37                           
#define mPara_SDPara38           247            //SD驱动器参数38                           
#define mPara_SDPara39           248            //SD驱动器参数39                           
#define mPara_SDPara40           249            //SD驱动器参数40                           
#define mPara_ESSDCurSel         250            //当前艾普希隆伺服驱动器序号选择                     
#define mPara_Peri_251           251            //                                    
#define mPara_Peri_252           252            //                                    
#define mPara_Peri_253           253            //                                    
#define mPara_Peri_254           254            //                                    
#define mPara_Peri_255           255            //                                    
#define mPara_Peri_256           256            //                                    
#define mPara_Peri_257           257            //                                    
#define mPara_Peri_258           258            //                                    
#define mPara_Peri_259           259            //                                    
#define mPara_ESParaRestMode     260            //ES驱动器参数复位                           
#define mPara_ESSetMaxRpm        261            //ES驱动器最高转速                           
#define mPara_ESSetMaxPres       262            //ES驱动器最高压力                           
#define mPara_ESSpeedBandwidth   263            //ES驱动器速度带宽                           
#define mPara_ESSetPresPercMax   264            //ES驱动器设置压力最大百分比                      
#define mPara_ESSetFlowPercMax   265            //ES驱动器设置流量最大百分比                      
#define mPara_ESSetPresPercMin   266            //ES驱动器设置压力最小百分比                      
#define mPara_ESSetFlowPercMin   267            //ES驱动器设置流量最小百分比                      
#define mPara_ESPGain1           268            //ES驱动器增益1                            
#define mPara_ESPGain2           269            //ES驱动器增益2                            
#define mPara_ESBasePres         270            //ES驱动器底压                             
#define mPara_ESMotorMaxFreq     271            //ES驱动器电机最大频率                         
#define mPara_ESMotorRatedFreq   272            //ES驱动器电机额定频率                         
#define mPara_ESMotorRatedVol    273            //ES驱动器电机额定电压                         
#define mPara_ESMotorRatedCur    274            //ES驱动器电机额定电流                         
#define mPara_ESMotorRatedPow    275            //ES驱动器电机额定功率                         
#define mPara_ESMotorRatedRpm    276            //ES驱动器电机额定转速                         
#define mPara_Peri_277           277            //                                    
#define mPara_ESMotorInertia     278            //ES驱动器电机惯量                           
#define mPara_Peri_279           279            //                                    
#define mPara_ESForwAndReveCon   280            //ES驱动器正反转控制                          
#define mPara_Peri_281           281            //                                    
#define mPara_ESMotorTempOver    282            //ES驱动器过温温度                           
#define mPara_ESMotorTempSnrType 283            //ES驱动器电机温度传感器类型                      
#define mPara_ESMotorPresSnrMinVol 284          //ES驱动器压力传感器最小电压                      
#define mPara_ESMotorParaSelfLearn 285          //ES驱动器电机参数自学习                        
#define mPara_ESPresConMode      286            //ES驱动器压力控制模式                         
#define mPara_ESBaseFlow         287            //ES驱动器底流                             
#define mPara_Peri_288           288            //                                    
#define mPara_Peri_289           289            //                                    
#define mPara_EuRaSDCurSel       290            //当前瑞欧伺服驱动器序号选择                       
#define mPara_Peri_291           291            //                                    
#define mPara_Peri_292           292            //                                    
#define mPara_Peri_293           293            //                                    
#define mPara_Peri_294           294            //                                    
#define mPara_Peri_295           295            //                                    
#define mPara_Peri_296           296            //                                    
#define mPara_Peri_297           297            //                                    
#define mPara_Peri_298           298            //                                    
#define mPara_Peri_299           299            //                                    
#define mPara_MD6InjPosMinAD     300            //注射位置最小AD                            
#define mPara_MD6InjPosMaxAD     301            //注射位置最大AD                            
#define mPara_MD6InjectStroke    302            //注射行程                                
#define mPara_MD6InjSwtHoldPresPos 303          //注射转保压位置                             
#define mPara_MD6InjSwtHoldPresTi 304           //注射转保压时间                             
#define mPara_MD6InjectSpdMax    305            //注射最大速度                              
#define mPara_MD6InjStartAccele  306            //注射开始加速时间                            
#define mPara_MD6InjEndDecele    307            //注射结束减速时间                            
#define mPara_MD6System1DriverSel 308           //系统1伺服选择                             
#define mPara_MD6DriverUseNum    309            //伺服使用数量                              
#define mPara_MD6HoldPres1Flow   310            //保压一段流量                              
#define mPara_MD6InjRespTi       311            //注射响应时间                              
#define mPara_MD6InjRespPos      312            //注射响应行程                              
#define mPara_MD6InjMoldMachCAN_ID 313          //塑机电脑CAN-ID                          
#define mPara_MD6Driver1CAN_ID   314            //驱动器1CAN-ID                          
#define mPara_MD6Driver2CAN_ID   315            //驱动器2CAN-ID                          
#define mPara_MD6Driver3CAN_ID   316            //驱动器3CAN-ID                          
#define mPara_MD6Driver4CAN_ID   317            //驱动器4CAN-ID                          
#define mPara_MD6SlaveSystemEN   318            //从系统启用使能                             
#define mPara_MD6MastSysMotorMaxRpm 319         //主系统电机最大转速                           
#define mPara_MD6SlaveSysMotorMaxRpm 320        //从系统电机最大转速                           
#define mPara_MD6GeneralPresKp   321            //常规动作压力环Kp                           
#define mPara_MD6GeneralPresKi   322            //常规动作压力环Ki                           
#define mPara_MD6GeneralPresKd   323            //常规动作压力环Kd                           
#define mPara_MD6SteadyPresKp    324            //稳态压力环Kp                             
#define mPara_MD6SteadyPresKi    325            //稳态压力环Ki                             
#define mPara_MD6SteadyPresKd    326            //稳态压力环Kd                             
#define mPara_MD6InjectPresKp    327            //注射压力环Kp                             
#define mPara_MD6InjectPresKi    328            //注射压力环Ki                             
#define mPara_MD6InjectPresKd    329            //注射压力环Kd                             
#define mPara_MD6PresRingRevLimit 330           //压力环反转限制                             
#define mPara_Peri_331           331            //                                    
#define mPara_Peri_332           332            //                                    
#define mPara_Peri_333           333            //                                    
#define mPara_Peri_334           334            //                                    
#define mPara_Peri_335           335            //                                    
#define mPara_Peri_336           336            //                                    
#define mPara_Peri_337           337            //                                    
#define mPara_Peri_338           338            //                                    
#define mPara_Peri_339           339            //                                    
#define mPara_Peri_340           340            //                                    
#define mPara_Peri_341           341            //                                    
#define mPara_Peri_342           342            //                                    
#define mPara_Peri_343           343            //                                    
#define mPara_Peri_344           344            //                                    
#define mPara_Peri_345           345            //                                    
#define mPara_Peri_346           346            //                                    
#define mPara_Peri_347           347            //                                    
#define mPara_Peri_348           348            //                                    
#define mPara_Peri_349           349            //                                    
#define mPara_Peri_350           350            //                                    
#define mPara_Peri_351           351            //                                    
#define mPara_Peri_352           352            //                                    
#define mPara_Peri_353           353            //                                    
#define mPara_Peri_354           354            //                                    
#define mPara_Peri_355           355            //                                    
#define mPara_Peri_356           356            //                                    
#define mPara_Peri_357           357            //                                    
#define mPara_Peri_358           358            //                                    
#define mPara_Peri_359           359            //                                    
#define mPara_Peri_360           360            //                                    
#define mPara_Peri_361           361            //                                    
#define mPara_Peri_362           362            //                                    
#define mPara_Peri_363           363            //                                    
#define mPara_Peri_364           364            //                                    
#define mPara_Peri_365           365            //                                    
#define mPara_Peri_366           366            //                                    
#define mPara_Peri_367           367            //                                    
#define mPara_Peri_368           368            //                                    
#define mPara_Peri_369           369            //                                    
#define mPara_Peri_370           370            //                                    
#define mPara_Peri_371           371            //                                    
#define mPara_Peri_372           372            //                                    
#define mPara_Peri_373           373            //                                    
#define mPara_Peri_374           374            //                                    
#define mPara_Peri_375           375            //                                    
#define mPara_Peri_376           376            //                                    
#define mPara_Peri_377           377            //                                    
#define mPara_Peri_378           378            //                                    
#define mPara_Peri_379           379            //                                    
#define mPara_Peri_380           380            //                                    
#define mPara_Peri_381           381            //                                    
#define mPara_Peri_382           382            //                                    
#define mPara_Peri_383           383            //                                    
#define mPara_Peri_384           384            //                                    
#define mPara_Peri_385           385            //                                    
#define mPara_Peri_386           386            //                                    
#define mPara_Peri_387           387            //                                    
#define mPara_Peri_388           388            //                                    
#define mPara_Peri_389           389            //                                    
#define mPara_Peri_390           390            //                                    
#define mPara_Peri_391           391            //                                    
#define mPara_Peri_392           392            //                                    
#define mPara_Peri_393           393            //                                    
#define mPara_Peri_394           394            //                                    
#define mPara_Peri_395           395            //                                    
#define mPara_Peri_396           396            //                                    
#define mPara_Peri_397           397            //                                    
#define mPara_Peri_398           398            //                                    
#define mPara_Peri_399           399            //                                    
#define mPara_Peri_400           400            //                                    
#define mPara_Peri_401           401            //                                    
#define mPara_Peri_402           402            //                                    
#define mPara_Peri_403           403            //                                    
#define mPara_Peri_404           404            //                                    
#define mPara_Peri_405           405            //                                    
#define mPara_Peri_406           406            //                                    
#define mPara_Peri_407           407            //                                    
#define mPara_Peri_408           408            //                                    
#define mPara_Peri_409           409            //                                    
#define mPara_Peri_410           410            //                                    
#define mPara_Peri_411           411            //                                    
#define mPara_Peri_412           412            //                                    
#define mPara_Peri_413           413            //                                    
#define mPara_Peri_414           414            //                                    
#define mPara_Peri_415           415            //                                    
#define mPara_Peri_416           416            //                                    
#define mPara_Peri_417           417            //                                    
#define mPara_Peri_418           418            //                                    
#define mPara_Peri_419           419            //                                    
#define mPara_Peri_420           420            //                                    
#define mPara_Peri_421           421            //                                    
#define mPara_Peri_422           422            //                                    
#define mPara_Peri_423           423            //                                    
#define mPara_Peri_424           424            //                                    
#define mPara_Peri_425           425            //                                    
#define mPara_Peri_426           426            //                                    
#define mPara_Peri_427           427            //                                    
#define mPara_Peri_428           428            //                                    
#define mPara_Peri_429           429            //                                    
#define mPara_Peri_430           430            //                                    
#define mPara_Peri_431           431            //                                    
#define mPara_Peri_432           432            //                                    
#define mPara_Peri_433           433            //                                    
#define mPara_Peri_434           434            //                                    
#define mPara_Peri_435           435            //                                    
#define mPara_Peri_436           436            //                                    
#define mPara_Peri_437           437            //                                    
#define mPara_Peri_438           438            //                                    
#define mPara_Peri_439           439            //                                    
#define mPara_Peri_440           440            //                                    
#define mPara_Peri_441           441            //                                    
#define mPara_Peri_442           442            //                                    
#define mPara_Peri_443           443            //                                    
#define mPara_Peri_444           444            //                                    
#define mPara_Peri_445           445            //                                    
#define mPara_Peri_446           446            //                                    
#define mPara_Peri_447           447            //                                    
#define mPara_Peri_448           448            //                                    
#define mPara_Peri_449           449            //                                    
#define mPara_Peri_450           450            //                                    
#define mPara_Peri_451           451            //                                    
#define mPara_Peri_452           452            //                                    
#define mPara_Peri_453           453            //                                    
#define mPara_Peri_454           454            //                                    
#define mPara_Peri_455           455            //                                    
#define mPara_Peri_456           456            //                                    
#define mPara_Peri_457           457            //                                    
#define mPara_Peri_458           458            //                                    
#define mPara_Peri_459           459            //                                    
#define mPara_Peri_460           460            //                                    
#define mPara_Peri_461           461            //                                    
#define mPara_Peri_462           462            //                                    
#define mPara_Peri_463           463            //                                    
#define mPara_Peri_464           464            //                                    
#define mPara_Peri_465           465            //                                    
#define mPara_Peri_466           466            //                                    
#define mPara_Peri_467           467            //                                    
#define mPara_Peri_468           468            //                                    
#define mPara_Peri_469           469            //                                    
#define mPara_Peri_470           470            //                                    
#define mPara_Peri_471           471            //                                    
#define mPara_Peri_472           472            //                                    
#define mPara_Peri_473           473            //                                    
#define mPara_Peri_474           474            //                                    
#define mPara_Peri_475           475            //                                    
#define mPara_Peri_476           476            //                                    
#define mPara_Peri_477           477            //                                    
#define mPara_Peri_478           478            //                                    
#define mPara_Peri_479           479            //                                    
#define mPara_Peri_480           480            //                                    
#define mPara_Peri_481           481            //                                    
#define mPara_Peri_482           482            //                                    
#define mPara_Peri_483           483            //                                    
#define mPara_Peri_484           484            //                                    
#define mPara_Peri_485           485            //                                    
#define mPara_Peri_486           486            //                                    
#define mPara_Peri_487           487            //                                    
#define mPara_Peri_488           488            //                                    
#define mPara_Peri_489           489            //                                    
#define mPara_Peri_490           490            //                                    
#define mPara_Peri_491           491            //                                    
#define mPara_Peri_492           492            //                                    
#define mPara_Peri_493           493            //                                    
#define mPara_Peri_494           494            //                                    
#define mPara_Peri_495           495            //                                    
#define mPara_Peri_496           496            //                                    
#define mPara_Peri_497           497            //                                    
#define mPara_Peri_498           498            //                                    
#define mPara_Peri_499           499            //                                    
#define mPara_Peri_500           500            //                                    
#define mPara_Peri_501           501            //                                    
#define mPara_Peri_502           502            //                                    
#define mPara_Peri_503           503            //                                    
#define mPara_Peri_504           504            //                                    
#define mPara_Peri_505           505            //                                    
#define mPara_Peri_506           506            //                                    
#define mPara_Peri_507           507            //                                    
#define mPara_Peri_508           508            //                                    
#define mPara_Peri_509           509            //                                    
#define mPara_Peri_510           510            //                                    
#define mPara_Peri_511           511            //                                    

//外设参数引用宏定义
#define Para_PeriParaSum         PeriPara[0]    //累加和校验码                              辅助用，下述机器参数累加和
#define Para_J6hHydrContrWord    PeriPara[1]    //液压控制字                               
#define Para_J6hSetFlow1         PeriPara[2]    //系统流量1                               
#define Para_J6hSetPres1         PeriPara[3]    //系统压力1                               
#define Para_J6hSetFlow2         PeriPara[4]    //系统流量2                               
#define Para_J6hSetPres2         PeriPara[5]    //系统压力2                               
#define Para_J6hSetFlow3         PeriPara[6]    //系统流量3                               
#define Para_J6hSetPres3         PeriPara[7]    //系统压力3                               
#define Para_J6hSetFlow4         PeriPara[8]    //系统流量4                               
#define Para_J6hSetPres4         PeriPara[9]    //系统压力4                               
#define Para_J6hActContrWord1    PeriPara[10]   //液压动作指令1                             
#define Para_J6hActContrWord2    PeriPara[11]   //液压动作指令2                             
#define Para_J6hActContrWord3    PeriPara[12]   //液压动作指令3                             
#define Para_J6hActContrWord4    PeriPara[13]   //液压动作指令4                             
#define Para_J6hHydrStatusWord   PeriPara[14]   //液压状态字                               
#define Para_J6hOutFlow1         PeriPara[15]   //输出速度1                               
#define Para_J6hCurrPres1        PeriPara[16]   //实际压力1                               
#define Para_J6hOutFlow2         PeriPara[17]   //输出速度2                               
#define Para_J6hCurrPres2        PeriPara[18]   //实际压力2                               
#define Para_J6hOutFlow3         PeriPara[19]   //输出速度3                               
#define Para_J6hCurrPres3        PeriPara[20]   //实际压力3                               
#define Para_J6hOutFlow4         PeriPara[21]   //输出速度4                               
#define Para_J6hCurrPres4        PeriPara[22]   //实际压力4                               
#define Para_J6hHardwareVer      PeriPara[23]   //硬件版本                                
#define Para_J6hSoftwareVer      PeriPara[24]   //软件版本                                
#define Para_J6hModelInfo        PeriPara[25]   //机型信息                                
#define Para_J6hNotConnDriver    PeriPara[26]   //主站未连接驱动器号记录                         
#define Para_J6hGeneralKP        PeriPara[27]   //通用KP                                
#define Para_J6hGeneralKI        PeriPara[28]   //通用KI                                
#define Para_J6hGeneralKD        PeriPara[29]   //通用KD                                
#define Para_J6hInjectKP         PeriPara[30]   //注射KP                                
#define Para_J6hInjectKI         PeriPara[31]   //注射KI                                
#define Para_J6hInjectKD         PeriPara[32]   //注射KD                                
#define Para_J6hHoldPresKP       PeriPara[33]   //保压KP                                
#define Para_J6hHoldPresKI       PeriPara[34]   //保压KI                                
#define Para_J6hHoldPresKD       PeriPara[35]   //保压KD                                
#define Para_J6hSetPres          PeriPara[36]   //设定压力                                
#define Para_J6hSetFlow          PeriPara[37]   //设定流量                                
#define Para_J6hOutTorque        PeriPara[38]   //输出扭矩                                
#define Para_J6hOutRev           PeriPara[39]   //输出转速                                
#define Para_J6hCurrPres         PeriPara[40]   //实际压力                                
#define Para_J6hMotionErr        PeriPara[41]   //运动卡error                            
#define Para_J6hParaConfirm      PeriPara[42]   //参数确认                                
#define Para_J6hHydrIndex        PeriPara[43]   //液压轴索引                               
#define Para_J6hDriverIndex      PeriPara[44]   //伺服轴索引                               
#define Para_J6hParaConfig       PeriPara[45]   //参数下载/备份/重置                          
#define Para_J6hZeroSeek         PeriPara[46]   //一键寻零/自学习                            
#define Para_J6hDisabled         PeriPara[47]   //断开使能                                
#define Para_J6hParaInOrOut      PeriPara[48]   //参数导入/导出                             
#define Para_J6hImportFile       PeriPara[49]   //导入文件选择                              
#define Para_J6hSensorMinVol     PeriPara[50]   //传感器最小电压                             
#define Para_J6hSensorMaxVol     PeriPara[51]   //传感器最大电压                             
#define Para_J6hSensorPresRat    PeriPara[52]   //传感器压力等级                             
#define Para_J6hPresCurrVol      PeriPara[53]   //压力传感器实际电压                           
#define Para_J6hPresAccele       PeriPara[54]   //压力环加速度                              
#define Para_J6hPresDecele       PeriPara[55]   //压力环减速度                              
#define Para_J6hFlowComp         PeriPara[56]   //给定流量补偿                              
#define Para_J6hPres1            PeriPara[57]   //1点压力                                
#define Para_J6hPres2            PeriPara[58]   //2点压力                                
#define Para_J6hPres3            PeriPara[59]   //3点压力                                
#define Para_J6hPres4            PeriPara[60]   //4点压力                                
#define Para_J6hPres5            PeriPara[61]   //5点压力                                
#define Para_J6hPres6            PeriPara[62]   //6点压力                                
#define Para_J6hPres7            PeriPara[63]   //7点压力                                
#define Para_J6hPres8            PeriPara[64]   //8点压力                                
#define Para_J6hCompFlow1        PeriPara[65]   //1点补偿流量                              
#define Para_J6hCompFlow2        PeriPara[66]   //2点补偿流量                              
#define Para_J6hCompFlow3        PeriPara[67]   //3点补偿流量                              
#define Para_J6hCompFlow4        PeriPara[68]   //4点补偿流量                              
#define Para_J6hCompFlow5        PeriPara[69]   //5点补偿流量                              
#define Para_J6hCompFlow6        PeriPara[70]   //6点补偿流量                              
#define Para_J6hCompFlow7        PeriPara[71]   //7点补偿流量                              
#define Para_J6hCompFlow8        PeriPara[72]   //8点补偿流量                              
#define Para_J6hTorqueSlope      PeriPara[73]   //扭矩释放斜率                              
#define Para_J6hUnderflow        PeriPara[74]   //底流                                  
#define Para_J6hPresContrLimit   PeriPara[75]   //压力控制上下限系数                           
#define Para_J6hMaxPresLoadTor   PeriPara[76]   //最大压力负载扭矩                            
#define Para_J6hPresRelTorque    PeriPara[77]   //泄压回拉扭矩                              
#define Para_J6hPresRelMxNRev    PeriPara[78]   //泄压最大负转速                             
#define Para_J6hEndPresRelTor    PeriPara[79]   //动作结束泄压扭矩系数                          
#define Para_J6hPresContrAccu    PeriPara[80]   //压力控制精度                              
#define Para_J6hHydrConWordSDO   PeriPara[81]   //液压控制字                               
#define Para_J6hEnInjRigid       PeriPara[82]   //注射刚性使能                              
#define Para_J6hInjRigidPres     PeriPara[83]   //注射刚性压力                              
#define Para_J6hSetSpeed         PeriPara[84]   //设定速度                                
#define Para_J6hEncoderSpeed     PeriPara[85]   //编码器速度                               
#define Para_J6hSetTorque        PeriPara[86]   //设定扭矩                                
#define Para_J6hCurrTorque       PeriPara[87]   //实际扭矩                                
#define Para_J6hApparCurrent     PeriPara[88]   //视在电流                                
#define Para_J6hCurrentPeak      PeriPara[89]   //电流尖峰值                               
#define Para_J6hGenerVol         PeriPara[90]   //母线电压                                
#define Para_J6hGenerVolPeak     PeriPara[91]   //母线电压尖峰值                             
#define Para_J6hCurrVol          PeriPara[92]   //实际输出电压                              
#define Para_J6hSpeedRing        PeriPara[93]   //速度环                                 
#define Para_J6hSwitchFreq       PeriPara[94]   //开关频率                                
#define Para_J6hEncoderType      PeriPara[95]   //编码器接口类型                             
#define Para_J6hMotorZero        PeriPara[96]   //电机零位                                
#define Para_J6hDirSelec         PeriPara[97]   //方向选择                                
#define Para_J6hEnableState      PeriPara[98]   //使能状态                                
#define Para_J6hDriverVer        PeriPara[99]   //驱动器版本                               
#define Para_J6hDriver1Temp      PeriPara[100]  //驱动器1温度                              
#define Para_J6hDriver2Temp      PeriPara[101]  //驱动器2温度                              
#define Para_J6hDriver3Temp      PeriPara[102]  //驱动器3温度                              
#define Para_J6hDriver4Temp      PeriPara[103]  //驱动器4温度                              
#define Para_J6hDriver5Temp      PeriPara[104]  //驱动器5温度                              
#define Para_J6hDriver6Temp      PeriPara[105]  //驱动器6温度                              
#define Para_J6hDriver7Temp      PeriPara[106]  //驱动器7温度                              
#define Para_J6hDriver8Temp      PeriPara[107]  //驱动器8温度                              
#define Para_J6hMotor1Temp       PeriPara[108]  //电机1温度                               
#define Para_J6hMotor2Temp       PeriPara[109]  //电机2温度                               
#define Para_J6hMotor3Temp       PeriPara[110]  //电机3温度                               
#define Para_J6hMotor4Temp       PeriPara[111]  //电机4温度                               
#define Para_J6hMotor5Temp       PeriPara[112]  //电机5温度                               
#define Para_J6hMotor6Temp       PeriPara[113]  //电机6温度                               
#define Para_J6hMotor7Temp       PeriPara[114]  //电机7温度                               
#define Para_J6hMotor8Temp       PeriPara[115]  //电机8温度                               
#define Para_J6hMaxSpeed         PeriPara[116]  //最大速度                                
#define Para_J6hTorqueFactor     PeriPara[117]  //扭矩因子                                
#define Para_J6hDriEarWarnTemp   PeriPara[118]  //驱动器预警温度                             
#define Para_J6hDriWarnTemp      PeriPara[119]  //驱动器报警温度                             
#define Para_J6hMotoEarWarnTemp  PeriPara[120]  //电机预警温度                              
#define Para_J6hDMotoWarnTemp    PeriPara[121]  //电机报警温度                              
#define Para_J6hDri1ErrCode      PeriPara[122]  //驱动器1故障代码                            
#define Para_J6hDri2ErrCode      PeriPara[123]  //驱动器2故障代码                            
#define Para_J6hDri3ErrCode      PeriPara[124]  //驱动器3故障代码                            
#define Para_J6hDri4ErrCode      PeriPara[125]  //驱动器4故障代码                            
#define Para_J6hDri5ErrCode      PeriPara[126]  //驱动器5故障代码                            
#define Para_J6hDri6ErrCode      PeriPara[127]  //驱动器6故障代码                            
#define Para_J6hDri7ErrCode      PeriPara[128]  //驱动器7故障代码                            
#define Para_J6hDri8ErrCode      PeriPara[129]  //驱动器8故障代码                            
#define Para_J6hDri9ErrCode      PeriPara[130]  //驱动器9故障代码                            
#define Para_J6hDri10ErrCode     PeriPara[131]  //驱动器10故障代码                           
#define Para_J6hDri11ErrCode     PeriPara[132]  //驱动器11故障代码                           
#define Para_J6hDri12ErrCode     PeriPara[133]  //驱动器12故障代码                           
#define Para_J6hDri13ErrCode     PeriPara[134]  //驱动器13故障代码                           
#define Para_J6hDri14ErrCode     PeriPara[135]  //驱动器14故障代码                           
#define Para_J6hDriSearchAdd     PeriPara[136]  //驱动器全地址搜索地址                          
#define Para_J6hDriSearchDat     PeriPara[137]  //驱动器全地址搜索内容                          
#define Para_Peri_138            PeriPara[138]  //                                    
#define Para_Peri_139            PeriPara[139]  //                                    
#define Para_Peri_140            PeriPara[140]  //                                    
#define Para_Peri_141            PeriPara[141]  //                                    
#define Para_Peri_142            PeriPara[142]  //                                    
#define Para_Peri_143            PeriPara[143]  //                                    
#define Para_Peri_144            PeriPara[144]  //                                    
#define Para_Peri_145            PeriPara[145]  //                                    
#define Para_Peri_146            PeriPara[146]  //                                    
#define Para_Peri_147            PeriPara[147]  //                                    
#define Para_Peri_148            PeriPara[148]  //                                    
#define Para_Peri_149            PeriPara[149]  //                                    
#define Para_Peri_150            PeriPara[150]  //                                    
#define Para_Peri_151            PeriPara[151]  //                                    
#define Para_Peri_152            PeriPara[152]  //                                    
#define Para_Peri_153            PeriPara[153]  //                                    
#define Para_Peri_154            PeriPara[154]  //                                    
#define Para_Peri_155            PeriPara[155]  //                                    
#define Para_Peri_156            PeriPara[156]  //                                    
#define Para_Peri_157            PeriPara[157]  //                                    
#define Para_Peri_158            PeriPara[158]  //                                    
#define Para_Peri_159            PeriPara[159]  //                                    
#define Para_Peri_160            PeriPara[160]  //                                    
#define Para_Peri_161            PeriPara[161]  //                                    
#define Para_Peri_162            PeriPara[162]  //                                    
#define Para_Peri_163            PeriPara[163]  //                                    
#define Para_Peri_164            PeriPara[164]  //                                    
#define Para_Peri_165            PeriPara[165]  //                                    
#define Para_Peri_166            PeriPara[166]  //                                    
#define Para_Peri_167            PeriPara[167]  //                                    
#define Para_Peri_168            PeriPara[168]  //                                    
#define Para_Peri_169            PeriPara[169]  //                                    
#define Para_Peri_170            PeriPara[170]  //                                    
#define Para_Peri_171            PeriPara[171]  //                                    
#define Para_Peri_172            PeriPara[172]  //                                    
#define Para_Peri_173            PeriPara[173]  //                                    
#define Para_Peri_174            PeriPara[174]  //                                    
#define Para_Peri_175            PeriPara[175]  //                                    
#define Para_Peri_176            PeriPara[176]  //                                    
#define Para_Peri_177            PeriPara[177]  //                                    
#define Para_Peri_178            PeriPara[178]  //                                    
#define Para_Peri_179            PeriPara[179]  //                                    
#define Para_Peri_180            PeriPara[180]  //                                    
#define Para_Peri_181            PeriPara[181]  //                                    
#define Para_Peri_182            PeriPara[182]  //                                    
#define Para_Peri_183            PeriPara[183]  //                                    
#define Para_Peri_184            PeriPara[184]  //                                    
#define Para_Peri_185            PeriPara[185]  //                                    
#define Para_Peri_186            PeriPara[186]  //                                    
#define Para_Peri_187            PeriPara[187]  //                                    
#define Para_Peri_188            PeriPara[188]  //                                    
#define Para_Peri_189            PeriPara[189]  //                                    
#define Para_Peri_190            PeriPara[190]  //                                    
#define Para_Peri_191            PeriPara[191]  //                                    
#define Para_Peri_192            PeriPara[192]  //                                    
#define Para_Peri_193            PeriPara[193]  //                                    
#define Para_Peri_194            PeriPara[194]  //                                    
#define Para_Peri_195            PeriPara[195]  //                                    
#define Para_Peri_196            PeriPara[196]  //                                    
#define Para_Peri_197            PeriPara[197]  //                                    
#define Para_Peri_198            PeriPara[198]  //                                    
#define Para_Peri_199            PeriPara[199]  //                                    
#define Para_TDSDCurSel          PeriPara[200]  //当前台达伺服驱动器序号选择                       
#define Para_TDSetPres           PeriPara[201]  //台达驱动器设置压力                           
#define Para_TDSetFlow           PeriPara[202]  //台达驱动器设置流量                           
#define Para_Peri_203            PeriPara[203]  //                                    
#define Para_Peri_204            PeriPara[204]  //                                    
#define Para_Peri_205            PeriPara[205]  //                                    
#define Para_Peri_206            PeriPara[206]  //                                    
#define Para_Peri_207            PeriPara[207]  //                                    
#define Para_Peri_208            PeriPara[208]  //                                    
#define Para_Peri_209            PeriPara[209]  //                                    
#define Para_SDParaRestMode      PeriPara[210]  //SD驱动器参数复位                           
#define Para_SDSetMaxRpm         PeriPara[211]  //SD驱动器最高转速                           
#define Para_SDSetMaxPres        PeriPara[212]  //SD驱动器最高压力                           
#define Para_SDSpeedBandwidth    PeriPara[213]  //SD驱动器速度带宽                           
#define Para_SDSetPresPercMax    PeriPara[214]  //SD驱动器设置压力最大百分比                      
#define Para_SDSetPresPercMid    PeriPara[215]  //SD驱动器设置压力中间百分比                      
#define Para_SDSetPresPercMin    PeriPara[216]  //SD驱动器设置压力最小百分比                      
#define Para_SDSetFlowPercMin    PeriPara[217]  //SD驱动器设置流量最小百分比                      
#define Para_SDPGain1            PeriPara[218]  //SD驱动器增益1                            
#define Para_SDPGain2            PeriPara[219]  //SD驱动器增益2                            
#define Para_SDBasePres          PeriPara[220]  //SD驱动器底压                             
#define Para_SDMotorMaxFreq      PeriPara[221]  //SD驱动器电机最大频率                         
#define Para_SDMotorRatedFreq    PeriPara[222]  //SD驱动器电机额定频率                         
#define Para_SDMotorRatedVol     PeriPara[223]  //SD驱动器电机额定电压                         
#define Para_SDMotorRatedCur     PeriPara[224]  //SD驱动器电机额定电流                         
#define Para_SDMotorRatedPow     PeriPara[225]  //SD驱动器电机额定功率                         
#define Para_SDMotorRatedRpm     PeriPara[226]  //SD驱动器电机额定转速                         
#define Para_SDMotorMagnPoleNum  PeriPara[227]  //SD驱动器电机额定磁极数                        
#define Para_SDMotorInertia      PeriPara[228]  //SD驱动器电机惯量                           
#define Para_SDSysInertia        PeriPara[229]  //SD驱动器系统惯量                           
#define Para_SDForwAndReveCon    PeriPara[230]  //SD驱动器正反转控制                          
#define Para_SDAlarmPcs          PeriPara[231]  //SD驱动器警报处理                           
#define Para_SDMotorTempOver     PeriPara[232]  //SD驱动器过温温度                           
#define Para_SDMotorTempSnrType  PeriPara[233]  //SD驱动器电机温度传感器类型                      
#define Para_SDMotorPresSnrMinVol PeriPara[234] //SD驱动器压力传感器最小电压                      
#define Para_SDMotorParaSelfLearn PeriPara[235] //SD驱动器电机参数自学习                        
#define Para_SDPresConMode       PeriPara[236]  //SD驱动器压力控制模式                         
#define Para_SDEnableResrSel     PeriPara[237]  //SD驱动器使能源选择                          
#define Para_SDPara29            PeriPara[238]  //SD驱动器参数29                           
#define Para_SDPara30            PeriPara[239]  //SD驱动器参数30                           
#define Para_SDPara31            PeriPara[240]  //SD驱动器参数31                           
#define Para_SDPara32            PeriPara[241]  //SD驱动器参数32                           
#define Para_SDPara33            PeriPara[242]  //SD驱动器参数33                           
#define Para_SDPara34            PeriPara[243]  //SD驱动器参数34                           
#define Para_SDPara35            PeriPara[244]  //SD驱动器参数35                           
#define Para_SDPara36            PeriPara[245]  //SD驱动器参数36                           
#define Para_SDPara37            PeriPara[246]  //SD驱动器参数37                           
#define Para_SDPara38            PeriPara[247]  //SD驱动器参数38                           
#define Para_SDPara39            PeriPara[248]  //SD驱动器参数39                           
#define Para_SDPara40            PeriPara[249]  //SD驱动器参数40                           
#define Para_ESSDCurSel          PeriPara[250]  //当前艾普希隆伺服驱动器序号选择                     
#define Para_Peri_251            PeriPara[251]  //                                    
#define Para_Peri_252            PeriPara[252]  //                                    
#define Para_Peri_253            PeriPara[253]  //                                    
#define Para_Peri_254            PeriPara[254]  //                                    
#define Para_Peri_255            PeriPara[255]  //                                    
#define Para_Peri_256            PeriPara[256]  //                                    
#define Para_Peri_257            PeriPara[257]  //                                    
#define Para_Peri_258            PeriPara[258]  //                                    
#define Para_Peri_259            PeriPara[259]  //                                    
#define Para_ESParaRestMode      PeriPara[260]  //ES驱动器参数复位                           
#define Para_ESSetMaxRpm         PeriPara[261]  //ES驱动器最高转速                           
#define Para_ESSetMaxPres        PeriPara[262]  //ES驱动器最高压力                           
#define Para_ESSpeedBandwidth    PeriPara[263]  //ES驱动器速度带宽                           
#define Para_ESSetPresPercMax    PeriPara[264]  //ES驱动器设置压力最大百分比                      
#define Para_ESSetFlowPercMax    PeriPara[265]  //ES驱动器设置流量最大百分比                      
#define Para_ESSetPresPercMin    PeriPara[266]  //ES驱动器设置压力最小百分比                      
#define Para_ESSetFlowPercMin    PeriPara[267]  //ES驱动器设置流量最小百分比                      
#define Para_ESPGain1            PeriPara[268]  //ES驱动器增益1                            
#define Para_ESPGain2            PeriPara[269]  //ES驱动器增益2                            
#define Para_ESBasePres          PeriPara[270]  //ES驱动器底压                             
#define Para_ESMotorMaxFreq      PeriPara[271]  //ES驱动器电机最大频率                         
#define Para_ESMotorRatedFreq    PeriPara[272]  //ES驱动器电机额定频率                         
#define Para_ESMotorRatedVol     PeriPara[273]  //ES驱动器电机额定电压                         
#define Para_ESMotorRatedCur     PeriPara[274]  //ES驱动器电机额定电流                         
#define Para_ESMotorRatedPow     PeriPara[275]  //ES驱动器电机额定功率                         
#define Para_ESMotorRatedRpm     PeriPara[276]  //ES驱动器电机额定转速                         
#define Para_Peri_277            PeriPara[277]  //                                    
#define Para_ESMotorInertia      PeriPara[278]  //ES驱动器电机惯量                           
#define Para_Peri_279            PeriPara[279]  //                                    
#define Para_ESForwAndReveCon    PeriPara[280]  //ES驱动器正反转控制                          
#define Para_Peri_281            PeriPara[281]  //                                    
#define Para_ESMotorTempOver     PeriPara[282]  //ES驱动器过温温度                           
#define Para_ESMotorTempSnrType  PeriPara[283]  //ES驱动器电机温度传感器类型                      
#define Para_ESMotorPresSnrMinVol PeriPara[284] //ES驱动器压力传感器最小电压                      
#define Para_ESMotorParaSelfLearn PeriPara[285] //ES驱动器电机参数自学习                        
#define Para_ESPresConMode       PeriPara[286]  //ES驱动器压力控制模式                         
#define Para_ESBaseFlow          PeriPara[287]  //ES驱动器底流                             
#define Para_Peri_288            PeriPara[288]  //                                    
#define Para_Peri_289            PeriPara[289]  //                                    
#define Para_EuRaSDCurSel        PeriPara[290]  //当前瑞欧伺服驱动器序号选择                       
#define Para_Peri_291            PeriPara[291]  //                                    
#define Para_Peri_292            PeriPara[292]  //                                    
#define Para_Peri_293            PeriPara[293]  //                                    
#define Para_Peri_294            PeriPara[294]  //                                    
#define Para_Peri_295            PeriPara[295]  //                                    
#define Para_Peri_296            PeriPara[296]  //                                    
#define Para_Peri_297            PeriPara[297]  //                                    
#define Para_Peri_298            PeriPara[298]  //                                    
#define Para_Peri_299            PeriPara[299]  //                                    
#define Para_MD6InjPosMinAD      PeriPara[300]  //注射位置最小AD                            
#define Para_MD6InjPosMaxAD      PeriPara[301]  //注射位置最大AD                            
#define Para_MD6InjectStroke     PeriPara[302]  //注射行程                                
#define Para_MD6InjSwtHoldPresPos PeriPara[303] //注射转保压位置                             
#define Para_MD6InjSwtHoldPresTi PeriPara[304]  //注射转保压时间                             
#define Para_MD6InjectSpdMax     PeriPara[305]  //注射最大速度                              
#define Para_MD6InjStartAccele   PeriPara[306]  //注射开始加速时间                            
#define Para_MD6InjEndDecele     PeriPara[307]  //注射结束减速时间                            
#define Para_MD6System1DriverSel PeriPara[308]  //系统1伺服选择                             
#define Para_MD6DriverUseNum     PeriPara[309]  //伺服使用数量                              
#define Para_MD6HoldPres1Flow    PeriPara[310]  //保压一段流量                              
#define Para_MD6InjRespTi        PeriPara[311]  //注射响应时间                              
#define Para_MD6InjRespPos       PeriPara[312]  //注射响应行程                              
#define Para_MD6InjMoldMachCAN_ID PeriPara[313] //塑机电脑CAN-ID                          
#define Para_MD6Driver1CAN_ID    PeriPara[314]  //驱动器1CAN-ID                          
#define Para_MD6Driver2CAN_ID    PeriPara[315]  //驱动器2CAN-ID                          
#define Para_MD6Driver3CAN_ID    PeriPara[316]  //驱动器3CAN-ID                          
#define Para_MD6Driver4CAN_ID    PeriPara[317]  //驱动器4CAN-ID                          
#define Para_MD6SlaveSystemEN    PeriPara[318]  //从系统启用使能                             
#define Para_MD6MastSysMotorMaxRpm PeriPara[319]//主系统电机最大转速                           
#define Para_MD6SlaveSysMotorMaxRpm PeriPara[320]//从系统电机最大转速                          
#define Para_MD6GeneralPresKp    PeriPara[321]  //常规动作压力环Kp                           
#define Para_MD6GeneralPresKi    PeriPara[322]  //常规动作压力环Ki                           
#define Para_MD6GeneralPresKd    PeriPara[323]  //常规动作压力环Kd                           
#define Para_MD6SteadyPresKp     PeriPara[324]  //稳态压力环Kp                             
#define Para_MD6SteadyPresKi     PeriPara[325]  //稳态压力环Ki                             
#define Para_MD6SteadyPresKd     PeriPara[326]  //稳态压力环Kd                             
#define Para_MD6InjectPresKp     PeriPara[327]  //注射压力环Kp                             
#define Para_MD6InjectPresKi     PeriPara[328]  //注射压力环Ki                             
#define Para_MD6InjectPresKd     PeriPara[329]  //注射压力环Kd                             
#define Para_MD6PresRingRevLimit PeriPara[330]  //压力环反转限制                             
#define Para_Peri_331            PeriPara[331]  //                                    
#define Para_Peri_332            PeriPara[332]  //                                    
#define Para_Peri_333            PeriPara[333]  //                                    
#define Para_Peri_334            PeriPara[334]  //                                    
#define Para_Peri_335            PeriPara[335]  //                                    
#define Para_Peri_336            PeriPara[336]  //                                    
#define Para_Peri_337            PeriPara[337]  //                                    
#define Para_Peri_338            PeriPara[338]  //                                    
#define Para_Peri_339            PeriPara[339]  //                                    
#define Para_Peri_340            PeriPara[340]  //                                    
#define Para_Peri_341            PeriPara[341]  //                                    
#define Para_Peri_342            PeriPara[342]  //                                    
#define Para_Peri_343            PeriPara[343]  //                                    
#define Para_Peri_344            PeriPara[344]  //                                    
#define Para_Peri_345            PeriPara[345]  //                                    
#define Para_Peri_346            PeriPara[346]  //                                    
#define Para_Peri_347            PeriPara[347]  //                                    
#define Para_Peri_348            PeriPara[348]  //                                    
#define Para_Peri_349            PeriPara[349]  //                                    
#define Para_Peri_350            PeriPara[350]  //                                    
#define Para_Peri_351            PeriPara[351]  //                                    
#define Para_Peri_352            PeriPara[352]  //                                    
#define Para_Peri_353            PeriPara[353]  //                                    
#define Para_Peri_354            PeriPara[354]  //                                    
#define Para_Peri_355            PeriPara[355]  //                                    
#define Para_Peri_356            PeriPara[356]  //                                    
#define Para_Peri_357            PeriPara[357]  //                                    
#define Para_Peri_358            PeriPara[358]  //                                    
#define Para_Peri_359            PeriPara[359]  //                                    
#define Para_Peri_360            PeriPara[360]  //                                    
#define Para_Peri_361            PeriPara[361]  //                                    
#define Para_Peri_362            PeriPara[362]  //                                    
#define Para_Peri_363            PeriPara[363]  //                                    
#define Para_Peri_364            PeriPara[364]  //                                    
#define Para_Peri_365            PeriPara[365]  //                                    
#define Para_Peri_366            PeriPara[366]  //                                    
#define Para_Peri_367            PeriPara[367]  //                                    
#define Para_Peri_368            PeriPara[368]  //                                    
#define Para_Peri_369            PeriPara[369]  //                                    
#define Para_Peri_370            PeriPara[370]  //                                    
#define Para_Peri_371            PeriPara[371]  //                                    
#define Para_Peri_372            PeriPara[372]  //                                    
#define Para_Peri_373            PeriPara[373]  //                                    
#define Para_Peri_374            PeriPara[374]  //                                    
#define Para_Peri_375            PeriPara[375]  //                                    
#define Para_Peri_376            PeriPara[376]  //                                    
#define Para_Peri_377            PeriPara[377]  //                                    
#define Para_Peri_378            PeriPara[378]  //                                    
#define Para_Peri_379            PeriPara[379]  //                                    
#define Para_Peri_380            PeriPara[380]  //                                    
#define Para_Peri_381            PeriPara[381]  //                                    
#define Para_Peri_382            PeriPara[382]  //                                    
#define Para_Peri_383            PeriPara[383]  //                                    
#define Para_Peri_384            PeriPara[384]  //                                    
#define Para_Peri_385            PeriPara[385]  //                                    
#define Para_Peri_386            PeriPara[386]  //                                    
#define Para_Peri_387            PeriPara[387]  //                                    
#define Para_Peri_388            PeriPara[388]  //                                    
#define Para_Peri_389            PeriPara[389]  //                                    
#define Para_Peri_390            PeriPara[390]  //                                    
#define Para_Peri_391            PeriPara[391]  //                                    
#define Para_Peri_392            PeriPara[392]  //                                    
#define Para_Peri_393            PeriPara[393]  //                                    
#define Para_Peri_394            PeriPara[394]  //                                    
#define Para_Peri_395            PeriPara[395]  //                                    
#define Para_Peri_396            PeriPara[396]  //                                    
#define Para_Peri_397            PeriPara[397]  //                                    
#define Para_Peri_398            PeriPara[398]  //                                    
#define Para_Peri_399            PeriPara[399]  //                                    
#define Para_Peri_400            PeriPara[400]  //                                    
#define Para_Peri_401            PeriPara[401]  //                                    
#define Para_Peri_402            PeriPara[402]  //                                    
#define Para_Peri_403            PeriPara[403]  //                                    
#define Para_Peri_404            PeriPara[404]  //                                    
#define Para_Peri_405            PeriPara[405]  //                                    
#define Para_Peri_406            PeriPara[406]  //                                    
#define Para_Peri_407            PeriPara[407]  //                                    
#define Para_Peri_408            PeriPara[408]  //                                    
#define Para_Peri_409            PeriPara[409]  //                                    
#define Para_Peri_410            PeriPara[410]  //                                    
#define Para_Peri_411            PeriPara[411]  //                                    
#define Para_Peri_412            PeriPara[412]  //                                    
#define Para_Peri_413            PeriPara[413]  //                                    
#define Para_Peri_414            PeriPara[414]  //                                    
#define Para_Peri_415            PeriPara[415]  //                                    
#define Para_Peri_416            PeriPara[416]  //                                    
#define Para_Peri_417            PeriPara[417]  //                                    
#define Para_Peri_418            PeriPara[418]  //                                    
#define Para_Peri_419            PeriPara[419]  //                                    
#define Para_Peri_420            PeriPara[420]  //                                    
#define Para_Peri_421            PeriPara[421]  //                                    
#define Para_Peri_422            PeriPara[422]  //                                    
#define Para_Peri_423            PeriPara[423]  //                                    
#define Para_Peri_424            PeriPara[424]  //                                    
#define Para_Peri_425            PeriPara[425]  //                                    
#define Para_Peri_426            PeriPara[426]  //                                    
#define Para_Peri_427            PeriPara[427]  //                                    
#define Para_Peri_428            PeriPara[428]  //                                    
#define Para_Peri_429            PeriPara[429]  //                                    
#define Para_Peri_430            PeriPara[430]  //                                    
#define Para_Peri_431            PeriPara[431]  //                                    
#define Para_Peri_432            PeriPara[432]  //                                    
#define Para_Peri_433            PeriPara[433]  //                                    
#define Para_Peri_434            PeriPara[434]  //                                    
#define Para_Peri_435            PeriPara[435]  //                                    
#define Para_Peri_436            PeriPara[436]  //                                    
#define Para_Peri_437            PeriPara[437]  //                                    
#define Para_Peri_438            PeriPara[438]  //                                    
#define Para_Peri_439            PeriPara[439]  //                                    
#define Para_Peri_440            PeriPara[440]  //                                    
#define Para_Peri_441            PeriPara[441]  //                                    
#define Para_Peri_442            PeriPara[442]  //                                    
#define Para_Peri_443            PeriPara[443]  //                                    
#define Para_Peri_444            PeriPara[444]  //                                    
#define Para_Peri_445            PeriPara[445]  //                                    
#define Para_Peri_446            PeriPara[446]  //                                    
#define Para_Peri_447            PeriPara[447]  //                                    
#define Para_Peri_448            PeriPara[448]  //                                    
#define Para_Peri_449            PeriPara[449]  //                                    
#define Para_Peri_450            PeriPara[450]  //                                    
#define Para_Peri_451            PeriPara[451]  //                                    
#define Para_Peri_452            PeriPara[452]  //                                    
#define Para_Peri_453            PeriPara[453]  //                                    
#define Para_Peri_454            PeriPara[454]  //                                    
#define Para_Peri_455            PeriPara[455]  //                                    
#define Para_Peri_456            PeriPara[456]  //                                    
#define Para_Peri_457            PeriPara[457]  //                                    
#define Para_Peri_458            PeriPara[458]  //                                    
#define Para_Peri_459            PeriPara[459]  //                                    
#define Para_Peri_460            PeriPara[460]  //                                    
#define Para_Peri_461            PeriPara[461]  //                                    
#define Para_Peri_462            PeriPara[462]  //                                    
#define Para_Peri_463            PeriPara[463]  //                                    
#define Para_Peri_464            PeriPara[464]  //                                    
#define Para_Peri_465            PeriPara[465]  //                                    
#define Para_Peri_466            PeriPara[466]  //                                    
#define Para_Peri_467            PeriPara[467]  //                                    
#define Para_Peri_468            PeriPara[468]  //                                    
#define Para_Peri_469            PeriPara[469]  //                                    
#define Para_Peri_470            PeriPara[470]  //                                    
#define Para_Peri_471            PeriPara[471]  //                                    
#define Para_Peri_472            PeriPara[472]  //                                    
#define Para_Peri_473            PeriPara[473]  //                                    
#define Para_Peri_474            PeriPara[474]  //                                    
#define Para_Peri_475            PeriPara[475]  //                                    
#define Para_Peri_476            PeriPara[476]  //                                    
#define Para_Peri_477            PeriPara[477]  //                                    
#define Para_Peri_478            PeriPara[478]  //                                    
#define Para_Peri_479            PeriPara[479]  //                                    
#define Para_Peri_480            PeriPara[480]  //                                    
#define Para_Peri_481            PeriPara[481]  //                                    
#define Para_Peri_482            PeriPara[482]  //                                    
#define Para_Peri_483            PeriPara[483]  //                                    
#define Para_Peri_484            PeriPara[484]  //                                    
#define Para_Peri_485            PeriPara[485]  //                                    
#define Para_Peri_486            PeriPara[486]  //                                    
#define Para_Peri_487            PeriPara[487]  //                                    
#define Para_Peri_488            PeriPara[488]  //                                    
#define Para_Peri_489            PeriPara[489]  //                                    
#define Para_Peri_490            PeriPara[490]  //                                    
#define Para_Peri_491            PeriPara[491]  //                                    
#define Para_Peri_492            PeriPara[492]  //                                    
#define Para_Peri_493            PeriPara[493]  //                                    
#define Para_Peri_494            PeriPara[494]  //                                    
#define Para_Peri_495            PeriPara[495]  //                                    
#define Para_Peri_496            PeriPara[496]  //                                    
#define Para_Peri_497            PeriPara[497]  //                                    
#define Para_Peri_498            PeriPara[498]  //                                    
#define Para_Peri_499            PeriPara[499]  //                                    
#define Para_Peri_500            PeriPara[500]  //                                    
#define Para_Peri_501            PeriPara[501]  //                                    
#define Para_Peri_502            PeriPara[502]  //                                    
#define Para_Peri_503            PeriPara[503]  //                                    
#define Para_Peri_504            PeriPara[504]  //                                    
#define Para_Peri_505            PeriPara[505]  //                                    
#define Para_Peri_506            PeriPara[506]  //                                    
#define Para_Peri_507            PeriPara[507]  //                                    
#define Para_Peri_508            PeriPara[508]  //                                    
#define Para_Peri_509            PeriPara[509]  //                                    
#define Para_Peri_510            PeriPara[510]  //                                    
#define Para_Peri_511            PeriPara[511]  //                                    

#endif
